# Generated by Django 4.1.8 on 2023-07-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_media_remove_post_images_remove_post_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(upload_to=''),
        ),
    ]
